sudo: required
language: generic
services:
  - docker


before_install:
  - docker build -t afed29/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true afed29/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-357099032582"
  path_name: "docker-react"
  on:
    branch: "master"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
